### ISSUE TITLE
Support inline commands in .yml

### ISSUE THREAD

**Issue by StarpTech** [platdesign/node-compose#11]
```
process_a:
  run: "gulp task"
  cwd: ./webapp
  environment:
    - NODE_ENV=development
```

Use cases:
- start gulp tasks
- start simple one liner e.g "localtunnel" (https://localtunnel.me/)

Is this already possible or we have to extend this? Thanks.
